spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/auth/**
          - id: company-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/companies/**
          - id: financial-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/financial/**

server:
  port: 8080
